### ISSUE TITLE
Code for F6 menu esx_policejob

### ISSUE THREAD

**Issue by RobijnGit** [RichMilly/FiveM-Pepper-Spray#2]
Hey, i want this in F6 menu for esx_policejob,

u can press f6 and goto pepperspray and you have it, so that esx_policejob is the only one who can ge the pepperspray

sorry for bad english

**Comment by SoulReaper4720** [comment]
> 
> 
> Hey, i want this in F6 menu for esx_policejob,
> 
> u can press f6 and goto pepperspray and you have it, so that esx_policejob is the only one who can ge the pepperspray
> 
> sorry for bad english

Good idea, however I think that you have to post this in "Pull Request"?
